from datetime import datetime
from decimal import Decimal, InvalidOperation
from typing import Any

from app.database.enums import PaymentMethod
from app.database.models.transaction import Transaction
from app.database.repositories.transaction import TransactionRepository
from app.utils.timezone import (
    get_month_window,
    get_range_window,
    get_today_window,
    get_week_window,
    parse_date,
    sgt_to_utc,
)


class InvalidEditValue(ValueError):
    """Raised when an /edit value can't be coerced to its target type."""


class ExpenseService:
    def __init__(self):
        self.transaction_repo = TransactionRepository()

    async def add_transaction(
        self,
        user_id: int,
        amount: float | Decimal,
        merchant: str,
        payment_method: PaymentMethod,
        transaction_time: datetime,
        description: str | None = None,
        tag: str | None = None,
    ) -> Transaction:
        """Add a new transaction for a user.

        The category is auto-generated by the LLM (categorizer). If the
        LLM call fails or returns a value outside the allowed set, the
        transaction is still saved with ``category=NULL`` — categorisation
        is a soft dependency.
        """
        if not merchant:
            raise ValueError("Merchant is required")

        amount_decimal = Decimal(str(amount))
        transaction_time_utc = sgt_to_utc(transaction_time)

        # Auto-categorize. Never raise — fall back to NULL on failure.
        from app.services.categorizer import categorize

        category: str | None = None
        try:
            category = await categorize(merchant)
        except Exception:
            category = None

        return await self.transaction_repo.insert(
            user_id=user_id,
            amount=float(amount_decimal),
            merchant=merchant,
            payment_method=payment_method,
            transaction_time=transaction_time_utc,
            description=description,
            tag=tag,
            category=category,
        )

    async def delete_transaction(self, transaction_id: int, user_id: int) -> bool:
        """Delete a transaction (soft delete) if owned by user."""
        transaction = await self.transaction_repo.get_by_id_for_user(transaction_id, user_id)
        if not transaction:
            return False

        await self.transaction_repo.soft_delete(transaction)
        return True

    async def edit_transaction(
        self,
        transaction_id: int,
        user_id: int,
        field: str,
        value: Any,
    ) -> Transaction | None:
        """Edit a transaction field if owned by user."""
        allowed_fields = {"amount", "merchant", "description", "transaction_time", "tag", "category"}
        if field not in allowed_fields:
            raise ValueError(f"Field must be one of: {allowed_fields}")

        transaction = await self.transaction_repo.get_by_id_for_user(transaction_id, user_id)
        if not transaction:
            return None

        if field == "amount":
            try:
                value = float(Decimal(str(value)))
            except (InvalidOperation, ValueError, TypeError) as exc:
                raise InvalidEditValue(
                    f"Invalid amount: {value!r}. Use a number like 12.50 or -5.00 for refunds."
                ) from exc
        elif field == "transaction_time":
            if isinstance(value, str):
                try:
                    value = parse_date(value)
                except ValueError as exc:
                    raise InvalidEditValue(
                        f"Invalid date: {value!r}. Use YYYY-MM-DD."
                    ) from exc
            value = sgt_to_utc(value)

        await self.transaction_repo.update_field(transaction, field, value)
        return transaction

    async def get_latest_transactions(
        self, user_id: int, count: int = 10, tag: str | None = None
    ) -> list[Transaction]:
        """Get latest transactions for a user, optionally filtered by tag."""
        return await self.transaction_repo.list_latest_for_user(user_id, count, tag=tag)

    async def set_tag(
        self,
        transaction_id: int,
        user_id: int,
        tag: str | None,
    ) -> Transaction | None:
        """Set or clear the tag on a transaction.

        Returns the updated transaction, or ``None`` if the transaction
        doesn't exist (or isn't owned by the user).
        """
        return await self.edit_transaction(transaction_id, user_id, "tag", tag)

    async def recategorize(self, transaction_id: int, user_id: int) -> Transaction | None:
        """Re-run the LLM categorizer on a transaction and update the
        stored category.

        Returns the updated transaction, or ``None`` if the transaction
        doesn't exist (or isn't owned by the user). On LLM failure the
        row is left untouched (category stays NULL).
        """
        from app.services.categorizer import categorize

        transaction = await self.transaction_repo.get_by_id_for_user(
            transaction_id, user_id
        )
        if not transaction:
            return None

        try:
            new_category = await categorize(transaction.merchant)
        except Exception:
            new_category = None

        if new_category is not None:
            await self.transaction_repo.update_field(
                transaction, "category", new_category
            )
        return transaction

    async def get_today_spending(self, user_id: int, tag: str | None = None) -> float:
        """Get today's total spending (signed, including refunds)."""
        start, end = get_today_window()
        # Window is SGT; the DB stores UTC. Convert before querying.
        return await self.transaction_repo.sum_amount(
            user_id, sgt_to_utc(start), sgt_to_utc(end), tag=tag
        )

    async def get_week_spending(self, user_id: int, tag: str | None = None) -> float:
        """Get this week's total spending (signed, including refunds)."""
        start, end = get_week_window()
        return await self.transaction_repo.sum_amount(
            user_id, sgt_to_utc(start), sgt_to_utc(end), tag=tag
        )

    async def get_month_spending(self, user_id: int, tag: str | None = None) -> float:
        """Get this month's total spending (signed, including refunds)."""
        start, end = get_month_window()
        return await self.transaction_repo.sum_amount(
            user_id, sgt_to_utc(start), sgt_to_utc(end), tag=tag
        )

    async def search_transactions(
        self,
        user_id: int,
        merchant_substring: str,
        tag: str | None = None,
    ) -> list[Transaction]:
        """Search transactions by merchant name (case-insensitive)."""
        return await self.transaction_repo.search_transactions(
            user_id, merchant_substring, tag=tag
        )

    async def get_range_transactions(
        self,
        user_id: int,
        start_date: datetime | str,
        end_date: datetime | str,
        tag: str | None = None,
    ) -> tuple[list[Transaction], int, bool]:
        """Get transactions in a date range.

        Returns:
            Tuple of (transactions, total_count, is_truncated)
            where is_truncated is True if total_count > 200.
        """
        if isinstance(start_date, str):
            start_date = parse_date(start_date)
        if isinstance(end_date, str):
            end_date = parse_date(end_date)

        start_sgt, end_sgt = get_range_window(start_date, end_date)
        # Convert SGT window to UTC — the DB stores transaction_time as UTC.
        rows, total_count = await self.transaction_repo.list_in_range_for_user(
            user_id, sgt_to_utc(start_sgt), sgt_to_utc(end_sgt), tag=tag
        )
        return rows, total_count, total_count > 200
