version: "3.8"

services:
  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
    env_file:
      - .env
    networks:
      - expense-network
    depends_on:
      - mysql
